"""add question_id in quiz_answers ForeignKey

Revision ID: 031a7cbc5392
Revises: 7230dd2e8a99
Create Date: 2025-11-30 09:48:06.647700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '031a7cbc5392'
down_revision: Union[str, Sequence[str], None] = '7230dd2e8a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_result_id', sa.Integer(), nullable=False, comment='クイズ結果IDの外部キー'),
    sa.Column('question_num', sa.Integer(), nullable=False, comment='何問目か'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='問題ID'),
    sa.Column('choice_id', sa.Integer(), nullable=False, comment='選んだ選択肢のID'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='正解したか'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_result_id'], ['quiz_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz-answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz-answers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_result_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='クイズ結果IDの外部キー'),
    sa.Column('question_num', mysql.INTEGER(), autoincrement=False, nullable=False, comment='何問目か'),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='問題ID'),
    sa.Column('choice_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='選んだ選択肢のID'),
    sa.Column('is_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='正解したか'),
    sa.Column('create_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_result_id'], ['quiz_results.id'], name=op.f('quiz-answers_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('quiz_answers')
    # ### end Alembic commands ###
