"""fix column name typo

Revision ID: 321f7ccbcb48
Revises: 8e003cb93a4c
Create Date: 2025-12-11 19:11:32.663157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '321f7ccbcb48'
down_revision: Union[str, Sequence[str], None] = '8e003cb93a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourist_spots', sa.Column('available_time', sa.String(length=100), nullable=True, comment='利用可能時間'))
    op.drop_column('tourist_spots', 'availavle_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourist_spots', sa.Column('availavle_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='利用可能時間'))
    op.drop_column('tourist_spots', 'available_time')
    # ### end Alembic commands ###
