"""Create tables

Revision ID: 5acf13abc929
Revises: 
Create Date: 2025-12-11 20:50:42.067170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acf13abc929'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gourmet_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='店舗名'),
    sa.Column('detail', sa.Text(), nullable=False, comment='概要'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='住所'),
    sa.Column('lat', sa.String(length=100), nullable=True, comment='緯度'),
    sa.Column('lon', sa.String(length=100), nullable=True, comment='経度'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='区分'),
    sa.Column('tokusanhin', sa.String(length=255), nullable=True, comment='特産品'),
    sa.Column('start_time', sa.String(length=100), nullable=True, comment='開始時間'),
    sa.Column('finish_time', sa.String(length=100), nullable=True, comment='終了時間'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('hp_url', sa.Text(), nullable=True, comment='ホームページURL'),
    sa.Column('img', sa.Text(), nullable=True, comment='画像'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_type', sa.String(length=100), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tourist_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='観光地名'),
    sa.Column('detail', sa.Text(), nullable=False, comment='概要'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='住所'),
    sa.Column('lat', sa.String(length=100), nullable=True, comment='緯度'),
    sa.Column('lon', sa.String(length=100), nullable=True, comment='経度'),
    sa.Column('available_time', sa.String(length=100), nullable=True, comment='利用可能時間'),
    sa.Column('closure_info', sa.Text(), nullable=True, comment='休業情報'),
    sa.Column('start_time', sa.String(length=100), nullable=True, comment='開始時間'),
    sa.Column('finish_time', sa.String(length=100), nullable=True, comment='終了時間'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('tel', sa.String(length=100), nullable=True, comment='電話番号'),
    sa.Column('hp_url', sa.Text(), nullable=True, comment='ホームページURL'),
    sa.Column('img', sa.Text(), nullable=True, comment='画像'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='ユーザー名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='パスワード'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーIDの外部キー'),
    sa.Column('spot_type', sa.String(length=100), nullable=False, comment='tourist or gourmet'),
    sa.Column('spot_id', sa.Integer(), nullable=False, comment='touristかgourmetのID'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_type', 'spot_id', name='unique_user_spot_interest'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ユーザーIDの外部キー'),
    sa.Column('spot_type', sa.String(length=100), nullable=False, comment='tourist or gourmet'),
    sa.Column('score', sa.Integer(), nullable=False, comment='正解した問題数'),
    sa.Column('total_questions', sa.Integer(), nullable=False, comment='出題数'),
    sa.Column('play_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True, comment='プレイした日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_result_id', sa.Integer(), nullable=False, comment='クイズ結果IDの外部キー'),
    sa.Column('question_num', sa.Integer(), nullable=False, comment='何問目か'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='問題ID'),
    sa.Column('choice_id', sa.Integer(), nullable=False, comment='選んだ選択肢のID'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='正解したか'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_result_id'], ['quiz_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    op.drop_table('quiz_results')
    op.drop_table('interests')
    op.drop_table('users')
    op.drop_table('tourist_spots')
    op.drop_table('questions')
    op.drop_table('gourmet_spots')
    # ### end Alembic commands ###
