"""lat and lon column change data type

Revision ID: ccb85684f558
Revises: 5acf13abc929
Create Date: 2025-12-17 21:33:00.732381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccb85684f558'
down_revision: Union[str, Sequence[str], None] = '5acf13abc929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gourmet_spots', 'lat',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.DECIMAL(precision=9, scale=6),
               existing_comment='緯度',
               existing_nullable=True)
    op.alter_column('gourmet_spots', 'lon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.DECIMAL(precision=9, scale=6),
               existing_comment='経度',
               existing_nullable=True)
    op.alter_column('tourist_spots', 'lat',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.DECIMAL(precision=9, scale=6),
               existing_comment='緯度',
               existing_nullable=True)
    op.alter_column('tourist_spots', 'lon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.DECIMAL(precision=9, scale=6),
               existing_comment='経度',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tourist_spots', 'lon',
               existing_type=sa.DECIMAL(precision=9, scale=6),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='経度',
               existing_nullable=True)
    op.alter_column('tourist_spots', 'lat',
               existing_type=sa.DECIMAL(precision=9, scale=6),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='緯度',
               existing_nullable=True)
    op.alter_column('gourmet_spots', 'lon',
               existing_type=sa.DECIMAL(precision=9, scale=6),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='経度',
               existing_nullable=True)
    op.alter_column('gourmet_spots', 'lat',
               existing_type=sa.DECIMAL(precision=9, scale=6),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='緯度',
               existing_nullable=True)
    # ### end Alembic commands ###
