"""Create tourist_spots, gourmet_spots, questions tables

Revision ID: dfa5d875eacc
Revises: 
Create Date: 2025-11-19 15:15:27.637497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa5d875eacc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gourmet_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='店舗名'),
    sa.Column('detail', sa.Text(), nullable=False, comment='概要'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='住所'),
    sa.Column('lat', sa.String(length=100), nullable=True, comment='緯度'),
    sa.Column('lon', sa.String(length=100), nullable=True, comment='経度'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='区分'),
    sa.Column('tokusanhin', sa.String(length=255), nullable=True, comment='特産品'),
    sa.Column('start_time', sa.String(length=100), nullable=True, comment='開始時間'),
    sa.Column('finish_time', sa.String(length=100), nullable=True, comment='終了時間'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('hp_url', sa.Text(), nullable=True, comment='ホームページURL'),
    sa.Column('img', sa.Text(), nullable=True, comment='画像'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_type', sa.String(length=100), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tourist_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='観光地名'),
    sa.Column('detail', sa.Text(), nullable=False, comment='概要'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='住所'),
    sa.Column('lat', sa.String(length=100), nullable=True, comment='緯度'),
    sa.Column('lon', sa.String(length=100), nullable=True, comment='経度'),
    sa.Column('availavle_time', sa.String(length=100), nullable=True, comment='利用可能時間'),
    sa.Column('closure_info', sa.Text(), nullable=True, comment='休業情報'),
    sa.Column('start_time', sa.String(length=100), nullable=True, comment='開始時間'),
    sa.Column('finish_time', sa.String(length=100), nullable=True, comment='終了時間'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('tel', sa.String(length=100), nullable=True, comment='電話番号'),
    sa.Column('hp_url', sa.Text(), nullable=True, comment='ホームページURL'),
    sa.Column('img', sa.Text(), nullable=True, comment='画像'),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourist_spots')
    op.drop_table('questions')
    op.drop_table('gourmet_spots')
    # ### end Alembic commands ###
